name: Deploy to Render

on:
  push:
    branches:
      - chapter-5-step-5  # Ou qualquer branch que você deseja monitorar para deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Build project (se necessário)
      run: yarn build

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}  # API Key do Render
      run: |
        curl -X POST \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -d '{"branch": "chapter-5-step-5"}' \
          https://api.render.com/v1/services/{SERVICE_ID}/deploy
